-- System catalog: not custom, no owner
INSERT INTO exercises (name, muscle_group, equipment, is_custom, created_by) VALUES
('Bench Press', 'chest', 'barbell', FALSE, NULL),
('Incline Bench Press', 'chest', 'barbell', FALSE, NULL),
('Incline DB Press', 'chest', 'dumbbell', FALSE, NULL),
('Dumbbell Bench Press', 'chest', 'dumbbell', FALSE, NULL),
('Cable Fly', 'chest', 'cable', FALSE, NULL),
('Push Up', 'chest', 'bodyweight', FALSE, NULL),
('Dip', 'chest', 'bodyweight', FALSE, NULL),
('Squat', 'legs', 'barbell', FALSE, NULL),
('Front Squat', 'legs', 'barbell', FALSE, NULL),
('Leg Press', 'legs', 'machine', FALSE, NULL),
('Romanian Deadlift', 'legs', 'barbell', FALSE, NULL),
('Leg Curl', 'legs', 'machine', FALSE, NULL),
('Leg Extension', 'legs', 'machine', FALSE, NULL),
('Walking Lunge', 'legs', 'dumbbell', FALSE, NULL),
('Bulgarian Split Squat', 'legs', 'dumbbell', FALSE, NULL),
('Hip Thrust', 'legs', 'barbell', FALSE, NULL),
('Calf Raise', 'legs', 'machine', FALSE, NULL),
('Deadlift', 'back', 'barbell', FALSE, NULL),
('Sumo Deadlift', 'back', 'barbell', FALSE, NULL),
('Pull Up', 'back', 'bodyweight', FALSE, NULL),
('Chin Up', 'back', 'bodyweight', FALSE, NULL),
('Lat Pulldown', 'back', 'machine', FALSE, NULL),
('Barbell Row', 'back', 'barbell', FALSE, NULL),
('Pendlay Row', 'back', 'barbell', FALSE, NULL),
('Dumbbell Row', 'back', 'dumbbell', FALSE, NULL),
('Cable Row', 'back', 'cable', FALSE, NULL),
('T-Bar Row', 'back', 'machine', FALSE, NULL),
('Face Pull', 'back', 'cable', FALSE, NULL),
('Row', 'back', 'cable', FALSE, NULL),
('OHP', 'shoulders', 'barbell', FALSE, NULL),
('Overhead Press', 'shoulders', 'barbell', FALSE, NULL),
('Dumbbell Shoulder Press', 'shoulders', 'dumbbell', FALSE, NULL),
('Lateral Raise', 'shoulders', 'dumbbell', FALSE, NULL),
('Front Raise', 'shoulders', 'dumbbell', FALSE, NULL),
('Rear Delt Fly', 'shoulders', 'dumbbell', FALSE, NULL),
('Arnold Press', 'shoulders', 'dumbbell', FALSE, NULL),
('Curls', 'arms', 'dumbbell', FALSE, NULL),
('Barbell Curl', 'arms', 'barbell', FALSE, NULL),
('Hammer Curl', 'arms', 'dumbbell', FALSE, NULL),
('Preacher Curl', 'arms', 'machine', FALSE, NULL),
('Triceps Pushdown', 'arms', 'cable', FALSE, NULL),
('Skull Crusher', 'arms', 'barbell', FALSE, NULL),
('Overhead Triceps Extension', 'arms', 'dumbbell', FALSE, NULL),
('Close Grip Bench Press', 'arms', 'barbell', FALSE, NULL),
('Plank', 'core', 'bodyweight', FALSE, NULL),
('Hanging Leg Raise', 'core', 'bodyweight', FALSE, NULL),
('Cable Crunch', 'core', 'cable', FALSE, NULL),
('Farmer Carry', 'full_body', 'dumbbell', FALSE, NULL),
('Kettlebell Swing', 'full_body', 'kettlebell', FALSE, NULL);
